# Build properties.
build:
  # Directory where you what drush make to build your site code base. Used like
  # this: drush make path/to/build/file <target>
  target: docroot
  # Parent make file for building code base (and including any other relevant make
  # files). Used like this: drush make <build_file> docroot
  build_file: build.make
  # Options will be passed to drush make exactly how they're written here, like this:
  # drush make build.make docroot --option1 --option2 --option3=a,b,c ... --optionN

prebuild-commands:
# - 'shell command 1 goes here'
# - 'shell command 2 goes here'

# Custom commands. These are run after subtrees are updated and after the drush make
# rebuild runs, before any changes from drush make are committed.
postbuild-commands:
  - 'rm -rf docroot/sites/default; cd docroot/sites; ln -s ../../symlink-these/default default'
  - 'rm -rf docroot/.htaccess; cd docroot/; ln -s ../symlink-these/.htaccess .htaccess'
  - 'rm -rf docroot/robots.txt; cd docroot/; ln -s ../symlink-these/robots.txt robots.txt'
  # If your site includes libraries installed by composer (e.g. composer_autoload
  # or guzzle module) you'll want to include something like this:
  # - 'cd docroot/sites/all/modules/guzzle; composer install;

# Custom properties supported by other Drush extensions (e.g. Drush Subtree) can
# go here.

